
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx9
  labels:
    app: ngnix-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: testenv
        image: tallapaneni/versions: latest
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: nginx9
spec:
  selector:
    app: nginx-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

