
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx12
  labels:
    app: ngnix-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: nginx-v2
        image: ${test}
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: nginx10
spec:
  selector:
    app: nginx-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

