
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx7
  labels:
    app: ngnix-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: testenv
        image: tallapaneni/versions:test
        ports:
        - containerPort: 80
