apiVersion: apps/v1
kind: Deployment
metadata:
   name: impetus-{{domain_prefix}}
   labels:
      app: impetus-{{domain_prefix}}
spec:
   replicas: 1
   selector:
      matchLabels:
           app:  impetus-{{domain_prefix}}
   template:
      metadata:
            labels:
               app:  impetus-{{domain_prefix}}
      spec:
          containers:
          - name: ramu
            image: gcr.io/projectkube-211818/projectkube-211818:{{git_branch}}-{{git_hash}}
            ports:
              - containerPort: 80
---
kind: Service
apiVersion: v1
metadata: 
  name:  impetus-{{domain_prefix}}
  labels:
     app:  impetus-{{domain_prefix}}
spec:
  type: ClusterIP
  selector:
     app:  impetus-{{domain_prefix}}
  ports:
  - port: 80
    targetPort: 80
---
           apiVersion: extensions/v1beta1
           kind: Ingress
           metadata:
              annotations:
                 kubernetes.io/ingress.class: nginx
                 nginx.ingress.kubernetes.io/rewrite-target: "/"
                 external-dns.alpha.kubernetes.io/hostname: {{domain_prefix}}.impetus.gq 
              name: {{domain_prefix}}-impetusgcp-com
              namespace: default
           spec:
             rules:
               - host: {{domain_prefix}}.impetus.gq  
                 http:
                   paths:
                     - path: /impetus-{{domain_prefix}}
                       backend:
                          serviceName:  impetus-{{domain_prefix}}
                          servicePort: 80
